### ISSUE TITLE
Git bash exe path select is not clear

### ISSUE THREAD

**Issue by KateOrient** [introfog/rGit#3]
1. It's not clear why the whole settings modal is opened if app only asks for the git bash exe path to be specified.
2. Suggestion: Ask for the git bash exe path on the first App run, not on the first cammand run.
3. Suggestion: Check if selected exe is a real Git bash exe.

**Comment by introfog** [comment]
`Suggestion: Check if selected exe is a real Git bash exe.`
Was converted to TODO in the code.
