### ISSUE TITLE
Rewrite running command to use native JavaFx javafx.concurrent.Task instead of java.lang.Thread

### ISSUE THREAD

**Issue by introfog** [introfog/rGit#8]
In `com.github.introfog.gitwave.controller.main.MainController#runCommand` i use `new Thread` to run command (it is necessary to do in a separate thread to keep main thread with app alive).
Running code in a different `java.lang.Thread` inside JavaFx application is not good idea, because you can't use any JavaFx logic, because you will get exception (not remember exactly which one).

So, in the scope of the issue, rewrite logic to use `javafx.concurrent.Task`, see example in `com.github.introfog.gitwave.controller.main.MenuController#createCheckForUpdateTask`

**Comment by AutumnRivera** [comment]
I've created a pull request to address this issue. 

https://github.com/introfog/GitWave/pull/12

**Comment by introfog** [comment]
Was fixed here https://github.com/introfog/GitWave/pull/12
Kudos @AutumnRivera
